#!/usr/bin/env python3
"""
Regenerates the auto-derived sections of HANDOFF.md from the repo itself.
Only rewrites content between AUTOGEN markers. Everything outside them is
hand-written and left alone.

Usage:  python tools/gen-handoff.py          (writes HANDOFF.md)
        python tools/gen-handoff.py --check  (exit 1 if stale; for CI)
"""
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "HANDOFF.md"
START = "<!-- AUTOGEN:START -->"
END = "<!-- AUTOGEN:END -->"


def sh(*args):
    try:
        return subprocess.run(
            args, cwd=ROOT, capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return ""


def schema_types(path):
    """Pull the distinct top-level JSON-LD @type values out of a page."""
    html = path.read_text(encoding="utf-8", errors="ignore")
    blocks = re.findall(
        r'<script type="application/ld\+json">(.*?)</script>', html, re.S
    )
    types = set()
    for b in blocks:
        try:
            data = json.loads(b)
        except json.JSONDecodeError:
            continue
        for item in data if isinstance(data, list) else [data]:
            if isinstance(item, dict) and "@type" in item:
                types.add(item["@type"])
    return sorted(types)


def page_title(path):
    html = path.read_text(encoding="utf-8", errors="ignore")
    m = re.search(r"<title>(.*?)</title>", html, re.S)
    return re.sub(r"\s+", " ", m.group(1)).strip() if m else ""


def collect(section):
    """Inventory the area/ or developments/ directories."""
    out = []
    base = ROOT / section
    if not base.is_dir():
        return out
    for d in sorted(p for p in base.iterdir() if p.is_dir()):
        page = d / "index.html"
        if not page.exists():
            continue
        gallery = d / "gallery"
        out.append(
            {
                "slug": d.name,
                "title": page_title(page),
                "lines": len(page.read_text(encoding="utf-8", errors="ignore").splitlines()),
                "photos": len(list(gallery.glob("*"))) if gallery.is_dir() else 0,
                "schema": schema_types(page),
            }
        )
    return out


def sitemap_urls():
    f = ROOT / "sitemap.xml"
    if not f.exists():
        return []
    return re.findall(r"<loc>(.*?)</loc>", f.read_text(encoding="utf-8"))


def redirects():
    f = ROOT / "netlify.toml"
    if not f.exists():
        return []
    text = f.read_text(encoding="utf-8")
    return [
        (a, b, c)
        for a, b, c in zip(
            re.findall(r'from\s*=\s*"(.*?)"', text),
            re.findall(r'to\s*=\s*"(.*?)"', text),
            re.findall(r"status\s*=\s*(\d+)", text),
        )
    ]


def hidden_sections():
    f = ROOT / "index.html"
    if not f.exists():
        return []
    html = f.read_text(encoding="utf-8", errors="ignore")
    return re.findall(r"<!--\s*HIDDEN\s*\(([^)]+)\)", html, re.I)


def analytics():
    """Which pages carry a GA4 tag, and which IDs are in use."""
    pages = [p for p in ROOT.rglob("*.html") if ".git" not in p.parts]
    ids, tagged = set(), 0
    for p in pages:
        s = p.read_text(encoding="utf-8", errors="ignore")
        found = set(re.findall(r"G-[A-Z0-9]{10}", s))
        if found:
            tagged += 1
            ids |= found
    return len(pages), tagged, sorted(ids)


def build():
    areas = collect("areas")
    devs = collect("developments")
    smap = sitemap_urls()
    total_pages, tagged, ga_ids = analytics()

    L = []
    a = L.append
    a(START)
    a("")
    a("<!-- Everything in this block is generated by tools/gen-handoff.py.")
    a("     Do not hand-edit. Edits will be overwritten on the next push to main. -->")
    a("")
    a("## Repo State (auto-generated)")
    a("")
    a(f"- Generated: `{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}`")
    a(f"- `main` HEAD: `{sh('git','rev-parse','--short','HEAD')}` "
      f"({sh('git','log','-1','--format=%ad','--date=short')}) "
      f"{sh('git','log','-1','--format=%s')}")
    a(f"- Total commits: {sh('git','rev-list','--count','HEAD')}")
    a(f"- Area pages: **{len(areas)}** | Development pages: **{len(devs)}** | "
      f"Galleries: **{sum(1 for d in devs if d['photos'])}** "
      f"({sum(d['photos'] for d in devs)} photos)")
    ga = f"{', '.join(ga_ids)} on {tagged}/{total_pages} pages" if ga_ids else "**none installed**"
    a(f"- Analytics: {ga}")
    a("")
    a("### Root files")
    a("")
    for p in sorted(ROOT.glob("*.html")):
        a(f"- `{p.name}` ({len(p.read_text(encoding='utf-8', errors='ignore').splitlines())} lines) "
          f"{page_title(p)}")
    a("")
    a("### Netlify redirects")
    a("")
    if redirects():
        for frm, to, status in redirects():
            a(f"- `{frm}` -> `{to}` ({status})")
    else:
        a("- none configured")
    a("")
    hs = hidden_sections()
    a("### Hidden homepage sections")
    a("")
    a("\n".join(f"- {h.strip()}" for h in hs) if hs else "- none")
    a("")
    a("### Area pages")
    a("")
    a("| Slug | URL | Schema |")
    a("|---|---|---|")
    for x in areas:
        a(f"| `{x['slug']}` | `/areas/{x['slug']}/` | {', '.join(x['schema'])} |")
    a("")
    a("### Development pages")
    a("")
    a("| Slug | URL | Gallery | Schema |")
    a("|---|---|---|---|")
    for x in devs:
        g = f"{x['photos']} photos" if x["photos"] else "**none**"
        a(f"| `{x['slug']}` | `/developments/{x['slug']}/` | {g} | {', '.join(x['schema'])} |")
    a("")
    # Consistency checks: the things that silently rot.
    a("### Consistency checks")
    a("")
    issues = []
    expected = (
        ["https://perlalutchman.com/"]
        + [f"https://perlalutchman.com/areas/{x['slug']}/" for x in areas]
        + [f"https://perlalutchman.com/developments/{x['slug']}/" for x in devs]
    )
    missing = [u for u in expected if u not in smap]
    orphan = [u for u in smap if u not in expected]
    if missing:
        issues.append(f"**sitemap.xml missing {len(missing)} URL(s):** "
                      + ", ".join(f"`{u}`" for u in missing))
    if orphan:
        issues.append(f"**sitemap.xml lists {len(orphan)} URL(s) with no page:** "
                      + ", ".join(f"`{u}`" for u in orphan))
    llms = (ROOT / "llms.txt").read_text(encoding="utf-8") if (ROOT / "llms.txt").exists() else ""
    absent = [x["slug"] for x in areas + devs if x["slug"] not in llms]
    if absent:
        issues.append(f"**llms.txt missing {len(absent)} page(s):** "
                      + ", ".join(f"`{s}`" for s in absent))
    home = (ROOT / "index.html").read_text(encoding="utf-8", errors="ignore")
    unlinked = [x["slug"] for x in areas + devs if x["slug"] not in home]
    if unlinked:
        issues.append(f"**not linked from homepage:** "
                      + ", ".join(f"`{s}`" for s in unlinked))
    nogallery = [x["slug"] for x in devs if not x["photos"]]
    if nogallery:
        issues.append(f"**development pages without a gallery ({len(nogallery)}):** "
                      + ", ".join(f"`{s}`" for s in nogallery))
    if ga_ids and tagged != total_pages:
        issues.append(f"**GA4 tag missing on {total_pages - tagged} of {total_pages} pages**")
    if len(ga_ids) > 1:
        issues.append(f"**more than one GA4 ID in use:** " + ", ".join(f"`{i}`" for i in ga_ids))
    if not ga_ids:
        issues.append("**no analytics tag on any page**")
    readme = (ROOT / "README.md").read_text(encoding="utf-8") if (ROOT / "README.md").exists() else ""
    for ref in ("real-estate.html",):
        if ref in readme and not (ROOT / ref).exists():
            issues.append(f"**README.md references `{ref}`, which does not exist**")
    a("\n".join(f"- {i}" for i in issues) if issues else "- All checks pass.")
    a("")
    a("### Recent commits")
    a("")
    a("```")
    a(sh("git", "log", "-12", "--pretty=%h %ad %s", "--date=short"))
    a("```")
    a("")
    a(END)
    return "\n".join(L)


def main():
    if not DOC.exists():
        print(f"error: {DOC} not found", file=sys.stderr)
        return 1
    current = DOC.read_text(encoding="utf-8")
    if START not in current or END not in current:
        print(f"error: AUTOGEN markers missing from {DOC.name}", file=sys.stderr)
        return 1
    updated = re.sub(
        re.escape(START) + r".*?" + re.escape(END), build(), current, flags=re.S
    )
    # Ignore the timestamp line when deciding whether anything really changed,
    # so CI doesn't commit a no-op on every run.
    strip_ts = lambda s: re.sub(r"- Generated: `.*?`", "", s)
    if "--check" in sys.argv:
        if strip_ts(updated) != strip_ts(current):
            print("HANDOFF.md is stale. Run: python tools/gen-handoff.py")
            return 1
        print("HANDOFF.md is current.")
        return 0
    if strip_ts(updated) == strip_ts(current):
        print("HANDOFF.md already current, no write.")
        return 0
    DOC.write_text(updated, encoding="utf-8")
    print("HANDOFF.md updated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
